apiVersion: apps/v1
kind: Deployment
metadata:
  name: employees-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: employees-app
  template:
    metadata:
      labels:
        app: employees-app
    spec:
      containers:
        - name: employees-app
          image: public.ecr.aws/x1l1i9y8/demoapplication:V2
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: employees-app-service
spec:
  selector:
    app: employees-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
